export const data = [
    {
      id: 1,
      name: "Carlos Martinez",
      gener: "Hombre",
      country: "México",
      state: "CDMX",
      avatar: "avatar_1.svg",
    },
    {
      id: 2,
      name: "Augusto Roberts",
      gener: "Hombre",
      country: "México",
      state: "CDMX",
      avatar: "avatar_2.svg",
    },
    {
      id: 3,
      name: "Camila Hernandez",
      gener: "Mujer",
      country: "México",
      state: "CDMX",
      avatar: "avatar_3.svg",
    },
    {
      id: 4,
      name: "Eduardo Jimenez",
      gener: "Hombre",
      country: "México",
      state: "CDMX",
      avatar: "avatar_4.svg",
    },
    {
      id: 5,
      name: "Gabriela Fuentes",
      gener: "Mujer",
      country: "México",
      state: "CDMX",
      avatar: "avatar_5.svg",
    },
    {
      id: 6,
      name: "Andrea Ordaz",
      gener: "Mujer",
      country: "México",
      state: "CDMX",
      avatar: "avatar_6.svg",
    },
    {
      id: 7,
      name: "Fernando García",
      gener: "Hombre",
      country: "México",
      state: "CDMX",
      avatar: "avatar_7.svg",
    },
  ];